services:
  database:
    container_name: feedback-app
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./app.env
volumes:
  pgdata:
  